# Patron Manager
# By ItzSave
#
# Permissions:
# patron.command.add
# patron.command.set
mysql_settings:
  host: "localhost"
  port: 3306 # Default port for MySQL is 3306.
  username: "root"
  password: ""
  database: "patrons"

# Valid actions are: [MESSAGE], [BROADCAST], [CONSOLE], [SOUND], [COMMAND]
patron_goals:
  '1':
    goal: 1000.0
    commands:
      - '[CONSOLE] eco give {player} 1000'
  '2':
    goal: 2000.0
    commands:
      - '[CONSOLE] eco give {player} 2000'
  '3':
    goal: 3000.0
    commands:
      - '[CONSOLE] eco give {player} 2000'
  '4':
    goal: 4000.0
    commands:
      - '[CONSOLE] eco give {player} 2000'
  '5':
    goal: 5000.0
    commands:
      - '[CONSOLE] eco give {player} 5000'

messages:
  balance_command: '&aYour patron balance is: &f${balance} &7[{percentage}%]'
  balance_added: '&aYou have added {balance} to {target}.'
  no_permission: '&cYou do not have permission to use this command.'
  balance_reset: '&aYou have reset {target} balance.'