name: PatronManager
version: '${version}'
main: net.zithium.patronmanager.PatronManager
api-version: '1.20'

depend:
  - LuckPerms

commands:
  patronadmin:
    description: 'Main command'
    usage: /<command>
    permission: patron.admin